
name: C/I
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '!.github/CI.yml'

permissions:
  id-token: write
  contents: read

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print
        run: echo "Main"
